"""Subagent collaboration helpers for the Agent learning workspace."""

from .team import (
    CollaborationPlan,
    SubagentContextBoundary,
    SubagentExecutionRecord,
    SubagentDelegationRecord,
    SubagentHandoffRecord,
    SubagentMessageEnvelope,
    SubagentSpec,
    SubagentStateTransition,
    SubagentTaskContract,
    SubagentReturnRecord,
    SubagentRuntimeSession,
    build_collaboration_plan,
    build_context_boundary,
    build_delegation_record,
    build_execution_record,
    build_handoff_record,
    build_message_envelope,
    build_runtime_session,
    build_state_transition,
    build_subagent_task_contract,
    build_return_record,
    describe_subagents,
    execute_collaboration_plan,
)

__all__ = [
    "CollaborationPlan",
    "SubagentContextBoundary",
    "SubagentExecutionRecord",
    "SubagentDelegationRecord",
    "SubagentHandoffRecord",
    "SubagentMessageEnvelope",
    "SubagentSpec",
    "SubagentStateTransition",
    "SubagentTaskContract",
    "SubagentReturnRecord",
    "SubagentRuntimeSession",
    "build_collaboration_plan",
    "build_context_boundary",
    "build_delegation_record",
    "build_execution_record",
    "build_handoff_record",
    "build_message_envelope",
    "build_runtime_session",
    "build_state_transition",
    "build_subagent_task_contract",
    "build_return_record",
    "describe_subagents",
    "execute_collaboration_plan",
]
