"""DeepSeek-grounded RAG answering built on local retrieval."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from .qa import answer_question
from .retrieval import SearchResult

if TYPE_CHECKING:
    from agent.llm import DeepSeekLLMClient


RAG_SYSTEM_PROMPT = (
    "You are a professional RAG assistant for an agent engineering project. "
    "Answer only from the provided context. "
    "If the context is insufficient, say that the local context is insufficient. "
    "Always mention the most relevant source labels."
)


@dataclass(frozen=True)
class GroundedRAGAnswer:
    """RAG answer generated by a real LLM with local source references."""

    question: str  # 用户问题
    answer: str  # DeepSeek 基于检索上下文生成的回答
    sources: list[str]  # 本次回答引用的本地来源

    def to_text(self) -> str:
        """Render the grounded answer with source labels."""

        source_text = "\n".join(f"- {source}" for source in self.sources) if self.sources else "- none"
        return f"Answer:\n{self.answer}\n\nSources:\n{source_text}"


def answer_question_with_llm(
    root: Path,
    question: str,
    *,
    top_k: int = 3,
    llm_client: DeepSeekLLMClient | None = None,
) -> GroundedRAGAnswer:
    """Retrieve local context and ask DeepSeek to generate a grounded answer."""

    retrieval_answer = answer_question(root, question, top_k=top_k)
    sources = [result.chunk.source_label() for result in retrieval_answer.results]

    if not retrieval_answer.results:
        return GroundedRAGAnswer(
            question=question,
            answer="The local context is insufficient to answer this question.",
            sources=[],
        )

    from agent.llm import DeepSeekLLMClient, LLMMessage

    client = llm_client or DeepSeekLLMClient()
    prompt = build_grounded_rag_prompt(question, retrieval_answer.results)
    response = client.chat(
        [
            LLMMessage(role="system", content=RAG_SYSTEM_PROMPT),
            LLMMessage(role="user", content=prompt),
        ]
    )
    return GroundedRAGAnswer(question=question, answer=response.content, sources=sources)


def build_grounded_rag_prompt(question: str, results: list[SearchResult]) -> str:
    """Build the user prompt that combines the question and retrieved context."""

    context_blocks: list[str] = []
    for index, result in enumerate(results, start=1):
        context_blocks.append(
            "\n".join(
                [
                    f"[Source {index}] {result.chunk.source_label()}",
                    f"Matched terms: {', '.join(result.matched_terms)}",
                    "Context:",
                    result.chunk.text,
                ]
            )
        )

    return (
        f"Question:\n{question}\n\n"
        "Local context:\n"
        f"{chr(10).join(context_blocks)}\n\n"
        "Instructions:\n"
        "- Answer the question using only the local context above.\n"
        "- Keep the answer concise and practical.\n"
        "- Cite source labels by name in the answer."
    )
